Various changes for setup and SAML

diff --git a/root-fs/app/bin/start-task b/root-fs/app/bin/start-task
--- a/root-fs/app/bin/start-task
+++ b/root-fs/app/bin/start-task
@@ -4,6 +4,10 @@ check-database
 if [ $? -ne 0 ]; then
 	date > /data/maintenance
 	run-installation
+	if [ $? -ne 0 ]; then
+		echo "Installation failed"
+		exit 1
+	fi
 	rm /data/maintenance
 else
 	date > /data/maintenance
